name: Build & Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- Clone repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Setup PHP & install Composer deps ---
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      # --- Setup Node.js & build assets ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies & Build
        run: |
            rm -f package-lock.json
            npm install
            npm run build

      - name: Remove excluded folders/files before deploy
        run: |
         rm -rf .git node_modules tests
         find . -name '*.log' -type f -delete

      - name: SFTP Deploy Laravel Core
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASS }}
          port: 22
          local_path: ./
          remote_path: /home/brownita/laravel

      - name: SFTP Deploy Laravel Public
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.CPANEL_FTP_HOST }}
          username: ${{ secrets.CPANEL_FTP_USER }}
          password: ${{ secrets.CPANEL_FTP_PASS }}
          port: 22
          local_path: ./public/*
          remote_path: /home/brownita/public_html
          
      # # # --- Deploy semua file ke cPanel ---
      # - name: SFTP Deploy
      #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      #   with:
      #     server: ${{ secrets.CPANEL_FTP_HOST }}      
      #     username: ${{ secrets.CPANEL_FTP_USER }}     
      #     password: ${{ secrets.CPANEL_FTP_PASS }}    
      #     port: 22                                  
      #     local_path: ./                            
      #     remote_path: /home/brownita/public_html/   
    
      # --- Generate .env di server ---
      - name: Create .env on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cat > /home/${{ secrets.CPANEL_USER }}/laravel/.env <<EOL
            APP_NAME=Brownita
            APP_ENV=${{ secrets.APP_ENV }}
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=${{ secrets.APP_DEBUG }}
            APP_URL=${{ secrets.APP_URL }}
        
            LOG_CHANNEL=stack
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug
        
            DB_CONNECTION=mysql
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=3306
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        
            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
        
            MEMCACHED_HOST=127.0.0.1
        
            REDIS_HOST=127.0.0.1
            REDIS_PASSWORD=null
            REDIS_PORT=6379
            EOL


      # --- Laravel optimize & migrate ---
      - name: Run Laravel Commands on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/${{ secrets.CPANEL_USER }}/laravel/
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache